version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11.2
    parallelism: 1
    working_directory: ~/react-pdf-example
    environment:
    steps:
      # - run: apk update && apk add git
      - checkout
      # - run: git submodule sync $$ git submodule update --init
      - attach_workspace:
          at: ~/react-pdf-example
      # - run: apk add --update python puthon-dev py-pip build-base
      # - run: pip install awscli
      - run: yarn install
      - run: yarn build
      - persist_to_workspace:
          root: .
          paths: dist
  deploy:
    docker:
      - image: circleci/goland:1.9.6
    parallelism: 1
    working_directory: ~/react-pdf-example
    steps:
      - checkout
      - attach_workspace:
          at: ~/react-pdf-example
      - run: go get -v github.com/MMichaelV/react-pdf-example
      - run:
        name: Deploy to S3
        command: |
          s3deploy -source=dist/ -region=us-east-1 -key=$AWS_ACCESS_KEY_ID -secret=$AWS_SECRET_ACCESS_KEY -bucket=$BUCKET_NAME
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
        filters:
          branches:
            only:
              - master
      - deploy:
        requires:
          - build:
            filters:
              branches:
                only:
                  - master

