version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11.2
    working_directory: ~/react-pdf-example
    environment:
    steps:
      - checkout
      # - attach_workspace:
      #     at: ~/react-pdf-example
      # - run: apk add --update python puthon-dev py-pip build-base
      # - run: pip install awscli
      - run: yarn install
      # run tests
      # - run: yarn run lint && yarn test
  deploy:
    docker:
      - image: circleci/node:8.11.2
    parallelism: 1
    working_directory: ~/react-pdf-example
    steps:
      - checkout
      - run: yarn install
      - run: sudo apt-get install awscli
      - run: aws s3 cp s3://mmv-serverless-packages/.env.react-example .env
      - run: ls -la
      - run: yarn build
      - run: aws s3 sync build/ s3://react-pdf-example --delete --region us-east-1
workflows:
  version: 2
  build-and-deploy:
    jobs:
#      - build:
#          filters:
#            branches:
#              only:
#                - master
      - deploy:
#          requires:
#            - build
          filters:
            branches:
              only:
                - master

